service:
  name: LeeSuHong
  phone: "010-5482-1212"
  sex: 'M'

---
spring.profiles: prod1,prod2

db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:1521/prod
  user: prod
  password: prod1234

---
spring.profiles: test1

db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:15211/test1
  user: test1
  password: test1
---
spring.profiles: test2

db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:15211/test2
  user: test2
  password: test2

---
spring.profiles: staging
db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//123.45.67.78:1521/staging
  user: staging
  password: staging

---
spring.profiles: local

db:
  driver: org.h2.Driver
  url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=2
  user: sa
  password: ""